site_name: 98336/98633 Documents
nav:
    #- Home: index.md
    - CVAI:
       - MD User Guide: NT9833X_MD_User_Guide_en.md
       - VPE IQ Tuning Guide: NT9833x_VPE_IQ_Tuning_Guide_en.md
theme:
  name: material
  highlightjs: true
  features:
    - search.highlight
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists
plugins:
  - search
use_directory_urls: false
